// Rebuild config/tokens.json from the official Binance lists (config/universe.json, made by discover.mjs)
// + Shariah screen (config/shariah.json). Core tickers keep full-ladder quoting every pass; the rest are
// "extended" (rotated, fewer sizes). Only tickers buyable via Ondo or bStocks are included.
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { ROOT } from '../src/env.mjs';
const rd = (f) => JSON.parse(readFileSync(join(ROOT, 'config', f), 'utf8'));
const uni = rd('universe.json').tickers, sh = rd('shariah.json'), old = rd('tokens.json');
const CORE = ['NVDA', 'AAPL', 'MSFT', 'GOOGL', 'TSLA', 'META', 'AMZN', 'SPY', 'QQQ'];
const FUNDS = new Set(['SPY', 'QQQ', 'IWM', 'VTI', 'IEMG', 'EWY', 'GLD', 'SOXX', 'SOXL', 'SOXS', 'TQQQ', 'SQQQ', 'JAAA', 'DRAM', 'STRC']);
const spus = new Set(sh.SPUS), hlal = new Set(sh.HLAL_top25);
const shariah = (t) => FUNDS.has(t) ? 'no (fund/ETF)' : spus.has(t) ? (hlal.has(t) ? 'SPUS+HLAL' : 'SPUS') : hlal.has(t) ? 'HLAL only (not in SPUS)' : 'not screened';
const tickers = {};
for (const [t, w] of Object.entries(uni).sort()) {
  if (!w.ondo && !w.bstocks) continue;                       // nothing buyable via aggregator
  const e = { tier: CORE.includes(t) ? 'core' : 'extended', shariah: shariah(t) };
  for (const k of ['ondo', 'bstocks', 'xstocks']) if (w[k]) e[k] = w[k].addr;
  if (w.xstocks) e.xsym = w.xstocks.symbol;
  tickers[t] = e;
}
const out = { _note: `generated by scripts/build-tokens.mjs from official Binance RWA lists (${rd('universe.json').at}) + ${sh.asOf} Shariah data`, chainId: 56, quote: old.quote, tickers };
writeFileSync(join(ROOT, 'config/tokens.json'), JSON.stringify(out, null, 2));
const n = Object.keys(tickers).length, scr = Object.values(tickers).filter(x => x.shariah.startsWith('SPUS')).length;
console.log(`tokens.json: ${n} tickers (${CORE.length} core), ${scr} Shariah-screened (SPUS)`);
// sanity: core addresses unchanged
for (const t of CORE) for (const k of ['ondo', 'bstocks', 'xstocks']) if (old.tickers[t]?.[k] && old.tickers[t][k].toLowerCase() !== tickers[t]?.[k]?.toLowerCase()) console.log('ADDRESS CHANGED', t, k);
